sudo: required
env:
  global:
    - CC_TEST_REPORTER_ID=a728598a72784cdb0b4ffddbb8e457cc8e699929af570894b8a110ccad1be9d2
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

before_install:
  - pyenv global 3.6.3
  - pip install flake8

language: ruby
rvm:
  - 2.4


after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
